name: flutter_application_1
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^4.5.0
  cloud_firestore: ^6.1.3
  firebase_auth: ^6.2.0
  local_auth: ^3.0.1
  excel: ^4.0.6
  path_provider: ^2.1.5
  open_file: ^3.3.0
  shared_preferences: ^2.3.5
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.10
  file_saver: ^0.3.1
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2  # Obligatoire pour le formatage des dates qu'on a ajouté
  csv: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/oms-logo.png
    - assets/images/icon.png
    - assets/images/icon1.png
    - assets/images/chantier+.png
    - assets/images/chantier-.svg
    - assets/images/CAPILog.png
    - assets/images/VSP.png


flutter_launcher_icons:
  image_path: "assets/images/icon.png"

  android: "launcher_icon"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"

  ios: true
