// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnoNI3uFlfVMMreWCALFokNu3Kulb5ZCc',
    appId: '1:638995538159:web:43cf9c4bcb235cacc4bb1a',
    messagingSenderId: '638995538159',
    projectId: 'consignes-interactives',
    authDomain: 'consignes-interactives.firebaseapp.com',
    storageBucket: 'consignes-interactives.firebasestorage.app',
    measurementId: 'G-M4Z3B25DTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2sG1HfbICs2sK72fepxG5-9sWDh93hZA',
    appId: '1:638995538159:android:485e3a58939ed80fc4bb1a',
    messagingSenderId: '638995538159',
    projectId: 'consignes-interactives',
    storageBucket: 'consignes-interactives.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNiF8xdDmC4nNrVhwViG-Bq7cQRDmFnrw',
    appId: '1:638995538159:ios:36444a1b9cf5627bc4bb1a',
    messagingSenderId: '638995538159',
    projectId: 'consignes-interactives',
    storageBucket: 'consignes-interactives.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNiF8xdDmC4nNrVhwViG-Bq7cQRDmFnrw',
    appId: '1:638995538159:ios:36444a1b9cf5627bc4bb1a',
    messagingSenderId: '638995538159',
    projectId: 'consignes-interactives',
    storageBucket: 'consignes-interactives.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnoNI3uFlfVMMreWCALFokNu3Kulb5ZCc',
    appId: '1:638995538159:web:9cac68fbbf39e9f6c4bb1a',
    messagingSenderId: '638995538159',
    projectId: 'consignes-interactives',
    authDomain: 'consignes-interactives.firebaseapp.com',
    storageBucket: 'consignes-interactives.firebasestorage.app',
    measurementId: 'G-03KR7MEGR8',
  );
}
